Repository CombatExtended-Continued/CombatExtended, pull requests merged in 2025-07, with the labels that each got.

#4022 Add impact clamors
  Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs
  Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
  Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_BunkerBuster.cs
  Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Flare.cs
  Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_SpawnsThing.cs
  Source/CombatExtended/Harmony/Harmony_NotifyClamorImpact.cs
Labels: Download in Comments

#4016 Update More Failing Transpiler Patches
  Source/CombatExtended/Harmony/Harmony_Fire.cs
  Source/CombatExtended/Harmony/Harmony_Hediff_Injury.cs
Labels: Download in Comments, 1.6

#3988 Convert comps to interval ticks
  Source/CombatExtended/CombatExtended/Comps/CompAmmoResupplyOnWakeup.cs
  Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs
  Source/CombatExtended/CombatExtended/Comps/CompInventory.cs
  Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs
  Source/CombatExtended/CombatExtended/Comps/CompTacticalManager.cs
  Source/CombatExtended/CombatExtended/Comps/CompThrownFleckEmitterSmooth.cs
  Source/CombatExtended/CombatExtended/Comps/HediffComp_InfecterCE.cs
  Source/CombatExtended/CombatExtended/Comps/HediffComp_Prometheum.cs
  Source/CombatExtended/CombatExtended/Comps/HediffComp_Stabilize.cs
  Source/CombatExtended/CombatExtended/Comps/HediffComp_Venom.cs
  Source/CombatExtended/CombatExtended/Projectiles/ArtilleryMarker.cs
  Source/CombatExtended/CombatExtended/Things/AmmoThing.cs
  Source/CombatExtended/CombatExtended/Things/Flare.cs
  Source/CombatExtended/CombatExtended/Things/IncendiaryFuel.cs
  Source/CombatExtended/CombatExtended/Things/Smoke.cs
  Source/CombatExtended/CombatExtended/WorldObjects/TravelingThing.cs
  Source/CombatExtended/Contrib/MechTakeAmmoCE/Core/CompMechAmmo.cs
Labels: Download in Comments, 1.6

#3981 Store default explosion falloff curve in a GameSetupStepDef
  Defs/GameSetupSteps/ExplosiveCurveSetup.xml
  Source/CombatExtended/CombatExtended/ExplosionCE.cs
  Source/CombatExtended/CombatExtended/GameSetupSteps/GameSetupStep_ExplosionCurve.cs
  Source/CombatExtended/CombatExtended/GenExplosionCE.cs
  Source/CombatExtended/Harmony/Harmony_CompExplosive.cs
Labels: Download in Comments, 1.6

#4030 Update references to AnimalBehaviours to target VEF.AnimalBehaviours
  ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Atispec.xml
  ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_EngorgedTentacularAberration.xml
  ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Gallatross.xml
  ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MoribundGallatross.xml
  ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_UnblinkingEye.xml
  ModPatches/Alpha Mechs/Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_PristineAssembler.xml
  ModPatches/The Joris Experience/Patches/The Joris Experience/Unique_Joris_Extended.xml
  ModPatches/The Joris Experience/Patches/The Joris Experience/Unique_Joris_Extended2.xml
  ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Durapod.xml
  ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Ironclad.xml
  ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Silverfish.xml
  ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Tankroach.xml
Labels: Download in Comments

#4041 Squash Viral's Bipod fixes
  Source/CombatExtended/CombatExtended/Comps/BipodComp.cs
  Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_BipodDisplay.cs
Labels: Download in Comments

#4033 Throw grenade tweaks
  Source/CombatExtended/CombatExtended/Verbs/Verb_ThrowGrenade.cs
Labels: Download in Comments

#4025 Archon VPE patch
  ModPatches/Vanilla Races Expanded - Archon/Patches/Vanilla Races Expanded - Archon/Abilities_Transcendent.xml
Labels: Download in Comments

#4027 Add 120mm Mortar Shell
  Defs/Ammo/Shell/120mmMortar.xml
Labels: Download in Comments

#4044 Update Nuget Packages
  Source/BetterTurretsCompat/BetterTurretsCompat.csproj
  Source/CombatExtended/CombatExtended.csproj
  Source/MiscTurretsCompat/MiscTurretsCompat.csproj
  Source/MultiplayerCompat/MultiplayerCompat.csproj
  Source/PsyblastersCompat/PsyblastersCompat.csproj
  Source/SOS2Compat/SOS2Compat.csproj
  Source/SRTSCompat/SRTSCompat.csproj
  Source/VehiclesCompat/VehiclesCompat.csproj
Labels: Download in Comments

#4024 New crafting category for RPG7 thermobaric rounds.
  Defs/Ammo/AmmoBases.xml
  Defs/Ammo/Rocket/57mmS5Rocket.xml
  Defs/Ammo/Rocket/83mmSMAW.xml
  Defs/Ammo/Rocket/84x246mmR.xml
  Defs/Ammo/Rocket/RPG32.xml
  Defs/Ammo/Rocket/RPG7.xml
  Defs/Ammo/Rocket/SPG9.xml
  Defs/ResearchProjectDefs/ResearchProjects.xml
  ModPatches/LF Red Dawn/Defs/LF Red Dawn/RPG29.xml
Labels: Download in Comments

#4048 Update Alpha Animals
  ModPatches/Alpha Animals/Defs/Alpha Animals/Defs_Ammo.xml
  ModPatches/Alpha Animals/Patches/Alpha Animals/AbilityDef/AlphaAnimals_CE_Patch_Abilities.xml
  ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Projectiles.xml
  ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_VerbShootCE.xml
  ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_VerbShootCE_Ideology.xml
Labels: Download in Comments

#4052 Update/streamline embrasure
  Defs/ThingDefs_Buildings/Buildings_Defenses.xml
Labels: Download in Comments

#4023 Patched Biotech tribal factions to have grenadiers and gunners
  Biotech/Patches/FactionDefs/Factions_Misc.xml
Labels: Download in Comments

#4054 Soft Armor Check
  Biotech/Patches/ThingDefs_Misc/Apparel_BiotechHeadgear.xml
  Defs/ThingDefs_Misc/Apparel_Headgear.xml
  Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
  Source/CombatExtended/CombatExtended/Defs/ApparelDefExtension.cs
Labels: Download in Comments

#4046 Initial Odyssey XML Patching Pass
  LoadFolders.xml
  Odyssey/Patches/Abilities/Abilities_Odyssey.xml
  Odyssey/Patches/Bodies/Crab.xml
  Odyssey/Patches/Bodies/Cyclops.xml
  Odyssey/Patches/Bodies/Drones/BodyParts_Drone.xml
  Odyssey/Patches/Bodies/Drones/Drone.xml
  Odyssey/Patches/Bodies/Drones/DroneWithThreads.xml
  Odyssey/Patches/Bodies/Drones/DroneWithThreeLegs.xml
  Odyssey/Patches/Bodies/Larva.xml
  Odyssey/Patches/Bodies/Pinniped/Pinniped.xml
  Odyssey/Patches/Bodies/Pinniped/PinnipedWithTusks.xml
  Odyssey/Patches/Bodies/Snail.xml
  Odyssey/Patches/DamageDefs.xml
  Odyssey/Patches/GeneDefs/GeneDefs_Odyssey.xml
  Odyssey/Patches/PawnkindDefs/PawnKinds_Odyssey.xml
  Odyssey/Patches/ThingDefs_Buildings/Buildings_Security.xml
  Odyssey/Patches/ThingDefs_Items/Items_Resource_Stuff_Leather.xml
  Odyssey/Patches/ThingDefs_Items/Items_Resources_Exotic.xml
  Odyssey/Patches/ThingDefs_Items/Items_Resources_Fish.xml
  Odyssey/Patches/ThingDefs_Items/Items_Resources_Misc.xml
  Odyssey/Patches/ThingDefs_Items/Items_Resources_Stuff.xml
  Odyssey/Patches/ThingDefs_Misc/Apparel_Odyssey.xml
  Odyssey/Patches/ThingDefs_Misc/Weapons_UniqueGuns.xml
  Odyssey/Patches/ThingDefs_Races/Races_Animals.xml
  Odyssey/Patches/ThingDefs_Races/Races_Animals_Bird.xml
  Odyssey/Patches/ThingDefs_Races/Races_Animals_Coastal.xml
  Odyssey/Patches/ThingDefs_Races/Races_Animals_Insects.xml
  Patches/Core/Bodies/BodyParts_Animal.xml
Labels: Download in Comments, Odyssey

#4059 Weapon proficiency patch
  LoadFolders.xml
  ModPatches/Weapon Proficiency/Patches/Weapon Proficiency/WP_stats.xml
  SupportedThirdPartyMods.md
Labels: Download in Comments

#4068 Fix MO Shield Texture
  ModPatches/Medieval Overhaul/Patches/Medieval Overhaul/ThingDefs_Misc/Shields/MO_Shields.xml
Labels: Download in Comments

#4064 Patch odyssey drones
  Odyssey/Defs/Ammo.xml
  Odyssey/Patches/ThingDefs_Misc/Ranged_Spacer.xml
  Odyssey/Patches/ThingDefs_Races/Races_Mechanoid.xml
  Source/CombatExtended/Harmony/Harmony_CompDHunterDrone.cs
Labels: Download in Comments

#4069 Fix Melee Target Gizmo
  Source/CombatExtended/CombatExtended/Comps/CompMeleeTargettingGizmo.cs
Labels: Download in Comments

#4057 Alpha biomes darts fix
  About/About.xml
  ModPatches/Alpha Biomes/Defs/Alpha Biomes/Defs_Ammo.xml
  ModPatches/Alpha Biomes/Patches/Alpha Biomes/RangedIndustrialGrenades.xml
  ModPatches/Alpha Biomes/Patches/Alpha Biomes/Tar_IED.xml
Labels: Download in Comments

#4073 Update VGE Patches
  ModPatches/Vanilla Genetics Expanded/Patches/Vanilla Genetics Expanded/AbilityDefs/VGE_CE_Patch_Abilities.xml
  ModPatches/Vanilla Genetics Expanded/Patches/Vanilla Genetics Expanded/Mods/AlphaAnimals_Patch_AbilityDefs.xml
  ModPatches/Vanilla Genetics Expanded/Patches/Vanilla Genetics Expanded/Mods/AlphaAnimals_Patch_VerbShoot.xml
  ModPatches/Vanilla Genetics Expanded/Patches/Vanilla Genetics Expanded/Patch_VerbShoot.xml
Labels: Download in Comments

#4075 Update Rimsenal Core Modular Helmets costlists
  ModPatches/Rimsenal Core/Patches/Rimsenal Core/Apparel_RS_CE.xml
Labels: Download in Comments

#4042 Preliminary Odyssey support
  Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs
  Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
  Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Labels: Download in Comments

#4085 Fix VWE patches
  ModPatches/Vanilla Weapons Expanded - Frontier/Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-Laser.xml
  ModPatches/Vanilla Weapons Expanded - Laser/Patches/Vanilla Weapons Expanded - Laser/RangedSpacer.xml
Labels: Download in Comments

#4082 Det's Half-Foot Initial Compatibility Patch
  LoadFolders.xml
  ModPatches/Det's Xenotypes - Half-foot/Patches/Det's Xenotypes - Half-foot/Apparel_Headgear.xml
  ModPatches/Det's Xenotypes - Half-foot/Patches/Det's Xenotypes - Half-foot/Weapon_Melee_Spacer.xml
  SupportedThirdPartyMods.md
Labels: Download in Comments

#4045 Implemented new weightedAmmoCategories field for LoadoutPropertiesExtension
  Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs
  Source/CombatExtended/CombatExtended/Defs/WeightedAmmoCategory.cs
Labels: Download in Comments

#4090 alpha mech enable the chaining effect
  ModPatches/Alpha Mechs/Patches/Alpha Mechs/Mods/Biotech/ThingDef_Misc/Weapons.xml
Labels: Download in Comments

#4043 AOC patch update
  ModPatches/AOC The Cleanup Devil/Defs/AOC The Cleanup Devil/Ammo_PowerCell.xml
  ModPatches/AOC The Cleanup Devil/Defs/AOC The Cleanup Devil/Projectiles_Devil.xml
  ModPatches/AOC The Cleanup Devil/Patches/AOC The Cleanup Devil/Animals.xml
  ModPatches/AOC The Cleanup Devil/Patches/AOC The Cleanup Devil/Apparel/Apparel.xml
  ModPatches/AOC The Cleanup Devil/Patches/AOC The Cleanup Devil/RangedWeapons.xml
  Textures/ThirdParty/AOC/Ammo/AOC_EMP/EMP_B.png
  Textures/ThirdParty/AOC/Ammo/AOC_EMP/EMP_C.png
  Textures/ThirdParty/AOC/Ammo/AOC_EMP/EMP_a.png
  Textures/ThirdParty/AOC/Ammo/AOC_HEAT/HEAT_B.png
  Textures/ThirdParty/AOC/Ammo/AOC_HEAT/HEAT_C.png
  Textures/ThirdParty/AOC/Ammo/AOC_HEAT/HEAT_a.png
  Textures/ThirdParty/AOC/Ammo/AOC_Thermobaric/Thermobaric_B.png
  Textures/ThirdParty/AOC/Ammo/AOC_Thermobaric/Thermobaric_C.png
  Textures/ThirdParty/AOC/Ammo/AOC_Thermobaric/Thermobaric_a.png
  Textures/ThirdParty/AOC/Projectile/AOC_EMP.png
  Textures/ThirdParty/AOC/Projectile/AOC_HEAT.png
  Textures/ThirdParty/AOC/Projectile/AOC_Thermobaric.png
Labels: Download in Comments

#4056 Odyssey Animals
  Odyssey/Patches/ThingDefs_Races/Races_Animals.xml
  Odyssey/Patches/ThingDefs_Races/Races_Animals_Coastal.xml
Labels: Odyssey

#4101 Rimsenal Vanilla 1.6
  ModPatches/Rimsenal Enhanced Vanilla/Defs/Rimsenal Enhanced Vanilla/Ammo_EnhancedVanilla.xml
  ModPatches/Rimsenal Enhanced Vanilla/Defs/Rimsenal Enhanced Vanilla/Ammo_EnhancedVanilla_Lasers.xml
  ModPatches/Rimsenal Enhanced Vanilla/Patches/Rimsenal Enhanced Vanilla/Weapons_Beam_CE.xml
  ModPatches/Rimsenal Enhanced Vanilla/Patches/Rimsenal Enhanced Vanilla/Weapons_Dumbfire_CE.xml
Labels: Download in Comments

#4093 Big and Small Genes 1.6 Patch
  ModPatches/Big and Small Genes/Defs/Big and Small Genes/Weapons/ThingDef_Ammo.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Big and Small - Enable All Optional Content/Weapons/Ammo_Mods.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Big and Small - Enable All Optional Content/Weapons/ThingDef_Building_Security.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Big and Small - Enable All Optional Content/Weapons/ThingDef_MeleeWeapons.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Big and Small - Enable All Optional Content/Weapons/ThingDef_Ranged.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Big and Small - Enable All Optional Content/Weapons/ThingDef_RangedNeolithic.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Big and Small - Enable All Optional Content/Weapons/ThingDef_Royalty_Weapons.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Big and Small - Enable All Optional Content/Weapons/ThingDef_Shrink.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Weapons/ThingDef_Building_Security.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Weapons/ThingDef_MeleeWeapons.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Weapons/ThingDef_Ranged.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Weapons/ThingDef_RangedNeolithic.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Weapons/ThingDef_Royalty_Weapons.xml
  ModPatches/Big and Small Genes/Patches/Big and Small Genes/Weapons/ThingDef_Shrink.xml
Labels: Download in Comments

#4065 Add 57x348mmSR Shell
  Defs/Ammo/Shell/57x348mmSR.xml
Labels: Download in Comments

#4098 Misstall apparel
  LoadFolders.xml
  ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Apparel.xml
  ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Armor.xml
  ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Head.xml
  ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_HeavyTurretpack.xml
  ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Loadbearing.xml
  ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Turretpack.xml
  SupportedThirdPartyMods.md
Labels: Download in Comments

#4115 Medieval Coastal Outfits patch
  LoadFolders.xml
  ModPatches/Medieval Coastal Outfits/Patches/Medieval Coastal Outfits/CE_MedievalCoastalOutfits.xml
  SupportedThirdPartyMods.md
Labels: Download in Comments

#4099 Re-add Nerfs and change inheritance/layers
  Biotech/Patches/ThingDefs_Misc/Apparel_BiotechHeadgear.xml
  Biotech/Patches/ThingDefs_Misc/Apparel_BiotechVarious.xml
Labels: Download in Comments

#4106 1.6 Rimsenal - GD underbarrel
  ModPatches/Rimsenal Core/Defs/Rimsenal Core/Ammo_GDGrenades.xml
  ModPatches/Rimsenal Core/Patches/Rimsenal Core/Ammo_GDGrenades.xml
  ModPatches/Rimsenal Core/Patches/Rimsenal Core/Weapons_GD_CE.xml
Labels: Download in Comments
